import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'

import Asset from '../components/Asset/index'
import Layout from '../components/Layout/index'
import Patrimony from '../components/Patrimony/index'
import Section from '../components/Section/index'
import Transaction from '../components/Transaction/index'
import { Content } from '../styles/pages/home'
import formatter from '../utils/formatter'

const Home: React.FC = () => {
    const [assets, setAssets] = useState([])
    const [fiisQuantity, setFiisQuantity] = useState(0)
    const [stockQuantity, setStockQuantity] = useState(0)
    const [fiisAmount, setFiisAmount] = useState(0)
    const [stockAmount, setStockAmount] = useState(0)

    useEffect(() => {
        // setAssets()
    }, [])

    return (
        <div>
        <Head>
            <title>My portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <Layout />
            <Patrimony />
            <Content>
                <Section title={"Ativos"} total={assets.length}>
                    <Asset
                            type={"Fundos Imobiliários"}
                            quantity={fiisQuantity}
                            value={formatter.format(fiisAmount)}
                            href={""}
                    />
                    <Asset
                            type={"Ações"}
                            quantity={stockQuantity}
                            value={formatter.format(stockAmount)}
                            href={""}
                    />
                </Section>
                <Section title={"Movimentações"}>
                    <Transaction
                            date={"10/10/22"}
                            ticker={"FUND11"}
                            quantity={4}
                            total={660}
                            value={165}
                            href={""}
                    />
                    <Transaction
                            date={"10/10/22"}
                            ticker={"FUND11"}
                            quantity={5}
                            total={655}
                            value={131}
                            href={""}
                    />
                    <Transaction
                            date={"10/10/22"}
                            ticker={"ACAO3"}
                            quantity={25}
                            total={661.50}
                            value={26.46}
                            href={""}
                    />
                    <Link href={''}>ver mais</Link>
                </Section>
                <Section title='Rentabilidade'>
                </Section>
                <Section title='Proventos'>
                </Section>

            </Content>
        </main>
        </div>
    )
}

export default Home
