import React, { useEffect, useState } from 'react'
import Head from '../../node_modules/next/head'
import Link from '../../node_modules/next/link'

import MyPortfolioLogo from '../assets/myPortfolio.svg'
import Asset from '../components/Asset/index'
import Layout from '../components/Layout/index'
import Patrimony from '../components/Patrimony/index'
import Section from '../components/Section/index'
import Transaction from '../components/Transaction/index'
import { Content } from '../styles/pages/home'
import formatter from '../utils/formatter'

const Home: React.FC = () => {
    const [assets, setAssets] = useState([])
    const [fiisQuantity, setFiisQuantity] = useState(0)
    const [stockQuantity, setStockQuantity] = useState(0)
    const [fiisAmount, setFiisAmount] = useState(0)
    const [stockAmount, setStockAmount] = useState(0)

    useEffect(() => {
        setAssets()
    }, [])
    const setUIValues = () => {
        assets.map(asset => {
            console.log(asset)
            // set fiis quantity
            if (asset.type === "fii") {
                const updated = fiisQuantity+1
                setFiisQuantity(updated)
            }
            // set stock quantity
            if (asset.type === "stock") {
                const updated = stockQuantity+1
                setFiisQuantity(updated)
            }
            // set fiis amount
            // set stock amount
        })
    }

    return (
        <div>
        <Head>
            <title>My portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <Layout />
            <Patrimony />
            <Content>
                <Section title={"Ativos"} total={assets.length}>
                    <Asset
                        type={"Fundos Imobiliários"}
                        quantity={fiisQuantity}
                        value={formatter.format(fiisAmount)}
                    />
                    <Asset
                        type={"Ações"}
                        quantity={stockQuantity}
                        value={formatter.format(stockAmount)}
                    />
                </Section>
                <Section title={"Movimentações"}>
                    <Transaction
                        date={"10/10/22"}
                        ticker={"FUND11"}
                        quantity={4}
                        total={660}
                        value={165}
                    />
                    <Transaction
                        date={"10/10/22"}
                        ticker={"FUND11"}
                        quantity={5}
                        total={655}
                        value={131}
                    />
                    <Transaction
                        date={"10/10/22"}
                        ticker={"ACAO3"}
                        quantity={25}
                        total={661.50}
                        value={26.46}
                    />
                    <Link href={''}>ver mais</Link>
                    {/* ver mais: grow on hover */}
                </Section>
                <Section title='Rentabilidade'>
                    {/* últimos 10 anos, últimos 5 anos, último ano, últimos 6 e 3 meses e último mês */}
                </Section>
                <Section title='Proventos'>
                    {/* último mês, mês atual */}
                </Section>

            </Content>
        </main>
        </div>
    )
}

export default Home
